### ISSUE TITLE
Map interrupt to specific cpu

### ISSUE THREAD

**Issue by FlTr** [Xilinx/embeddedsw#7] opened 2016-05-17 08:07 UTC
I think there is a error in the XScuGic_InterruptMapToCpu function. In my opinion there should be a binary AND instead of an OR to clear the previous settings first.

Before:

``` cpp
    RegValue = (RegValue | (~(0xFF << (Offset*8))) );
```

After:

``` cpp
    RegValue = (RegValue & (~(0xFF << (Offset*8))) );
```

Also it should be specified what is meant with **Cpu_Id**. Because for Zynq we need either 1 for CPU0 and 2 for CPU1

**Comment by kinjalp27** [comment] 2016-12-21 09:36
The issue is resolved in 2016.4 release.
CPU ID can be directly taken from xparameters.h as XPAR_CPU_ID. The necessary code changes are done and published with 2016.4 release.

**Closed** 2024-04-05 05:23 UTC
